### ISSUE TITLE
List of endpoints for an Azure AI Services resource

### ISSUE THREAD

**Issue by georgekosmidis** [jamesmcroft/bicep-templates#1]
Hello James!

Loved your repo, but i have one question!

In the following snippet: 
https://github.com/jamesmcroft/bicep-templates/blob/f711de7f1081b18d1bc707649c8c59b3ce9fc473/ai_ml/ai-services.bicep#L299, 
you are using `'OpenAI Language Model Instance API'` as an index for the `endpoints` array. Where did you find that? is there a list of these items somewhere? 

I deployed an  Azure AI services resource with bicep, and I need add to an Azure Function App i am deploying, environment variables towards the various endpoints.

Do you know where i can find that list?

Thank you!
George

**Comment by jamesmcroft** [comment]
@georgekosmidis thanks for reaching out. 

These endpoints aren't well documented now, but I can provide the current list. FYI, if you want to view these, you can find them in the Resource JSON for the Azure AI Service under the same `endpoints` property.

- OpenAI Language Model Instance API
- OpenAI Dall-E API
- OpenAI Whisper API
- OpenAI Model Scaleset API
- Token Service API
- Content Safety
- Container
- Computer Vision
- FormRecognizer
- Speech Services Speech to Text
- Speech Services Speech to Text v3.2
- Speech Services Speech to Text 2024-05-15-preview
- Speech Services Speech to Text v3.2_internal.1
- Speech Services Custom Voice
- Video Translation
- Speech Services Audio Content Creation
- Speech Services Custom Avatar
- Speech Services Batch Avatar
- Speech Services Batch Text to Speech
- Speech Services Speech to Text (Standard)
- Speech Services Text to Speech (Neural)
- Speech Services Speaker Verification
- Speech Services Speaker Identification
- Token
- Text Analytics
- Custom Text Authoring
- Conversational Language Understanding Authoring
- Custom Question Answering Authoring
- Custom Question Answering
- ConversationalLURuntime
- Language
- QnAMaker
- Turing
- QuestionAnswering
- LUIS
- TextTranslation-Global
- TextTranslation
- DocumentTranslation

It's important to note though, many of these AI services use the same `https://<your-resource>.cognitiveservices.azure.com` URL. Whereas the OpenAI specific endpoints provide the Azure OpenAI URL `https://<your-resource>.openai.azure.com`.

In general, you can use the `endpoint` property of the AI Service which is the `cognitiveservices.azure.com` URL.

**Comment by georgekosmidis** [comment]
Really appreciate your fast response!
I end up using `output aiServiceEndpoints string = string(aiServices.properties.endpoints)`

That returned the following list:
```
{
  "OpenAI Language Model Instance API": "https://swedencentral.api.cognitive.microsoft.com/",
  "OpenAI Dall-E API": "https://swedencentral.api.cognitive.microsoft.com/",
  "OpenAI Whisper API": "https://swedencentral.api.cognitive.microsoft.com/",
  "OpenAI Model Scaleset API": "https://swedencentral.api.cognitive.microsoft.com/",
  "Token Service API": "https://swedencentral.api.cognitive.microsoft.com/",
  "Content Safety": "https://swedencentral.api.cognitive.microsoft.com/",
  "Container": "https://swedencentral.api.cognitive.microsoft.com/",
  "Computer Vision": "https://swedencentral.api.cognitive.microsoft.com/",
  "FormRecognizer": "https://swedencentral.api.cognitive.microsoft.com/",
  "Speech Services Speech to Text": "https://swedencentral.api.cognitive.microsoft.com/",
  "Speech Services Speech to Text v3.2": "https://swedencentral.api.cognitive.microsoft.com/",
  "Speech Services Speech to Text 2024-05-15-preview": "https://swedencentral.api.cognitive.microsoft.com/",
  "Speech Services Speech to Text v3.2_internal.1": "https://swedencentral.api.cognitive.microsoft.com/",
  "Speech Services Custom Voice": "https://swedencentral.api.cognitive.microsoft.com/",
  "Video Translation": "https://swedencentral.api.cognitive.microsoft.com/",
  "Speech Services Audio Content Creation": "https://swedencentral.api.cognitive.microsoft.com/",
  "Speech Services Custom Avatar": "https://swedencentral.api.cognitive.microsoft.com/",
  "Speech Services Batch Avatar": "https://swedencentral.api.cognitive.microsoft.com/",
  "Speech Services Batch Text to Speech": "https://swedencentral.api.cognitive.microsoft.com/",
  "Speech Services Speech to Text (Standard)": "https://swedencentral.stt.speech.microsoft.com",
  "Speech Services Text to Speech (Neural)": "https://swedencentral.tts.speech.microsoft.com",
  "Speech Services Speaker Verification": "https://swedencentral.api.cognitive.microsoft.com/",
  "Speech Services Speaker Identification": "https://swedencentral.api.cognitive.microsoft.com/",
  "Token": "https://swedencentral.api.cognitive.microsoft.com/",
  "Text Analytics": "https://swedencentral.api.cognitive.microsoft.com/",
  "Custom Text Authoring": "https://swedencentral.api.cognitive.microsoft.com/",
  "Conversational Language Understanding Authoring": "https://swedencentral.api.cognitive.microsoft.com/",
  "Custom Question Answering Authoring": "https://swedencentral.api.cognitive.microsoft.com/",
  "Custom Question Answering": "https://swedencentral.api.cognitive.microsoft.com/",
  "ConversationalLURuntime": "https://swedencentral.api.cognitive.microsoft.com/",
  "Language": "https://swedencentral.api.cognitive.microsoft.com/",
  "QnAMaker": "https://swedencentral.api.cognitive.microsoft.com/",
  "Turing": "https://swedencentral.api.cognitive.microsoft.com/",
  "QuestionAnswering": "https://swedencentral.api.cognitive.microsoft.com/",
  "LUIS": "https://swedencentral.api.cognitive.microsoft.com/",
  "TextTranslation-Global": "https://api.cognitive.microsofttranslator.com/",
  "TextTranslation": "https://swedencentral.api.cognitive.microsoft.com/",
  "DocumentTranslation": "https://swedencentral.api.cognitive.microsoft.com/"
}
```

That was not what I was expecting! This is usually the common base URL that you can also get from `aiServices.properties.endpoint`.

What I was looking for was the endpoint including the path, something like the following list:

- **Document Intelligence**: https://swedencentral.api.cognitive.microsoft.com/formrecognizer/documentModels
- **Azure OpenAI**: https://swedencentral.api.cognitive.microsoft.com/openai/gpt-3.5-turbo
- **Cognitive Search**: https://swedencentral.api.cognitive.microsoft.com/search.indexes
- **Language Service**: https://swedencentral.api.cognitive.microsoft.com/language/:analyze-text
- **Translator**: https://swedencentral.api.cognitive.microsoft.com/translator/text/v3.0/translate
- **Face API:** https://swedencentral.api.cognitive.microsoft.com/face/v1.0/detect
- **Speech Service**: https://swedencentral.api.cognitive.microsoft.com/speech/v3.0/transcribe
- **Custom Vision**: https://swedencentral.api.cognitive.microsoft.com/customvision/training/v3.0/projects

Thank you :)
